/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to https://docs.gradle.org/9.3.1/userguide/multi_project_builds.html in the Gradle documentation.
 */

plugins {
    // Apply the foojay-resolver plugin to allow automatic download of JDKs
    id("org.gradle.toolchains.foojay-resolver-convention") version "1.0.0"
}

rootProject.name = "2026-lae-44d"

// Sub-projects:
include("week05:logger-basic")
include("week06:naive-mapper")
include("week06:naive-mapper-annotations")
include("week07:naive-mapper-recursive-and-generics")
include("week09:bench-and-jmh-sample")
include("week09:naive-mapper-bench")
include("week11:classfile-simple-sample")
include("week11:dynamic-mapper-without-reference-type")
include("week12:dynamic-mapper")